export const PATIENT_DATA = [
  {
    code: "ASD-5258",
    patientName: "Amit Bhardwaj",
    age: 32,
    gender: "Male",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: 2000,
  },
  {
    code: "ASD-5261",
    patientName: "Komal Singh",
    age: 28,
    gender: "Female",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: null,
  },
  {
    code: "ASD-5272",
    patientName: "Satish Dhar",
    age: 45,
    gender: "Male",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: null,
  },
  {
    code: "ASD-5253",
    patientName: "Kapil Sirohi",
    age: 36,
    gender: "Male",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: null,
  },
  {
    code: "ASD-5254",
    patientName: "Pankaj Gupta",
    age: 40,
    gender: "Male",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: 3000,
  },
  {
    code: "ASD-5262",
    patientName: "Komal Singh",
    age: 28,
    gender: "Female",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: null,
  },
];
