export const patientData = [
  {
    tokenNo: 1,
    code: "ASD-5258",
    patientName: "Amit Bhardwaj",
    age: 32,
    gender: "Male",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: 2000,
  },
  {
    tokenNo: 2,
    code: "ASD-5260",
    patientName: "Komal Singh",
    age: 28,
    gender: "Female",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: null,
  },
  {
    tokenNo: 3,
    code: "ASD-5272",
    patientName: "Satish Dhar",
    age: 45,
    gender: "Male",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: null,
  },
  {
    tokenNo: 4,
    code: "ASD-525",
    patientName: "Kapil Sirohi",
    age: 36,
    gender: "Male",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: null,
  },
  {
    tokenNo: 5,
    code: "ASD-525",
    patientName: "Pankaj Gupta",
    age: 40,
    gender: "Male",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: 3000,
  },
  {
    tokenNo: 6,
    code: "ASD-5260",
    patientName: "Komal Singh",
    age: 28,
    gender: "Female",
    address: "Sector 14, Dwarka, New Delhi",
    telephone: "9898989898",
    prevPaymentDetail: null,
  },
];
